name: Run Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt, rust-src

      - name: Run formatter (rustfmt)
        run: cargo fmt --check

      - name: Run linter (clippy)
        run: cargo clippy --lib --bin neko -- -D warnings

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Build release binary
        run: cargo build --release

      - name: Run tests
        run: tests/run.sh
